chore: git

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,10 +1,10 @@
 #!/bin/bash
 
 # 检查是否存在 "--no-verify" 选项
-if [ $? -ne 0 ]; then
-  echo "You may use \`git push --no-verify\` to skip this check."
-  exit 1
+ if [ $? -ne 0 ]; then
+  echo "Error running make check - please fix before committing"
+  echo "if this is a mistake you can skip the checks with 'git commit --no-verify'"
+  exit 0
 fi
-
 
 pnpm precommit
