xxx: xx

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,9 @@
+#!/bin/bash
+
+# 检查是否存在 "--no-verify" 选项
+if [[ $* == *--no-verify* ]]; then
+  echo "ERROR: Cannot use 'git commit --no-verify' command. Please remove '--no-verify' option."
+  exit 1
+fi
+
 pnpm precommit
